### ISSUE TITLE
"pip install fitter" Results in Error: "No such file or directory: 'requirements.txt'"

### ISSUE THREAD

**Issue by samuelchodur** [cokelaer/fitter#12]
```
$ pip install fitter
Collecting fitter
  Downloading https://files.pythonhosted.org/packages/ad/4d/2a899c9d617b3c1c05246d43581d82dfe3f108f74af55ea0bb741e720b45/fitter-1.1.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ma9vgdkb/fitter/setup.py", line 54, in <module>
        install_requires = open("requirements.txt").read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ma9vgdkb/fitter/


```

**Comment by ilyasst** [comment]
I've got the same error using Python 2.7

**Comment by athuljayaraj** [comment]
+1 on python3.6

**Comment by marianesalo** [comment]
+ 1 on python 3.7.1
I managed to install a previous version of the lib, though

**Comment by gforsyth** [comment]
The `requirements.txt` file needs to be added to the `MANIFEST.in` file so that it's present in the tarball on PyPI

**Comment by cokelaer** [comment]
done
