### ISSUE TITLE
AttributeError: Unknown property density when running summary()

### ISSUE THREAD

**Issue by Junshuai-Song** [cokelaer/fitter#18]
```
from fitter import Fitter
y2 = [0, 0, 1, 1, 2, 3, 4, 5, 6, 6, 6, 7, 8, 9, 9, 9, 9, 9, 10, 11, 13, 14, 16, 18]
f = Fitter(y2)
f.fit()
# may take some time since by default, all distributions are tried
# but you call manually provide a smaller set of distributions
f.summary()
print("test over!", flush=True)
exit(1)
```

**Comment by songjs1993** [comment]
All the given logs are as below:

```
Fitted wrapcauchy distribution with error=nan)
Traceback (most recent call last):
  File "/Users/songjs/Desktop/workspace/ecology-code/NeuRec-master/result_analysis/print_loss_act.py", line 158, in <module>
    impression_adjustment(color=colors[0], name=names[0])
  File "/Users/songjs/Desktop/workspace/ecology-code/NeuRec-master/result_analysis/print_loss_act.py", line 142, in impression_adjustment
    f.summary()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fitter/fitter.py", line 296, in summary
    self.hist()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fitter/fitter.py", line 194, in hist
    _ = pylab.hist(self._data, bins=self.bins, density=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/pyplot.py", line 3082, in hist
    stacked=stacked, data=data, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 1892, in inner
    return func(ax, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 6386, in hist
    p.update(kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/artist.py", line 885, in update
    for k, v in props.items()]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/artist.py", line 885, in <listcomp>
    for k, v in props.items()]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/artist.py", line 878, in _update_property
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property density

Process finished with exit code 1
```

**Comment by cokelaer** [comment]
what version of fitter and/or scipy are you using ? thanks

**Comment by cokelaer** [comment]
won't fix. This is probably a back-compat issue with scipy
