### ISSUE TITLE
AttributeError: 'Fitter' object has no attribute 'df_errors'

### ISSUE THREAD

**Issue by KarthikGanesan88** [cokelaer/fitter#53]
I just tried running Fitter as follows 

```
import numpy as np
from fitter import Fitter
x = np.random.rand(100)
f = Fitter(x)
f.summary()
```
and got this error:

```
File ".../python3.9/site-packages/fitter/fitter.py", line 380, in plot_pdf
  names = self.df_errors.sort_values(by=method).index[0:Nbest]
AttributeError: 'Fitter' object has no attribute 'df_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File ".../python3.9/site-packages/fitter/fitter.py", line 419, in summary
  self.plot_pdf(Nbest=Nbest, lw=lw, method=method)
File ".../python3.9/site-packages/fitter/fitter.py", line 382, in plot_pdf
  names = self.df_errors.sort(method).index[0:Nbest]
AttributeError: 'Fitter' object has no attribute 'df_errors'
```

**Comment by cokelaer** [comment]
@KarthikGanesan88 

thanks for using fitter. I believe, you need to fit the data before the summary():

    import numpy as np
    from fitter import Fitter
    x = np.random.rand(100)
    f = Fitter(x)

    f.fit()

    f.summary()

Like in this example: https://fitter.readthedocs.io/en/latest/tuto.html
